# Generated by Django 4.2.17 on 2025-01-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_remove_testimonial_project_testimonial_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-posted_on']},
        ),
    ]
