# Generated by Django 4.2.17 on 2025-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_alter_testimonial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
