# Generated by Django 4.2.17 on 2025-01-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Portfolio',
        ),
    ]
