# Generated by Django 4.2.17 on 2025-01-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_service_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
